{"id":11726,"className":"javax.naming.NamingException","methodName":"setRootCause","signature":"\u003cjavax.naming.NamingException: void setRootCause(java.lang.Throwable)\u003e","javadoc":"/** \n * Records the root cause of this NamingException. If \u003ctt\u003ee\u003c/tt\u003e is \u003ctt\u003ethis\u003c/tt\u003e, this method does not do anything. \u003cp\u003e This method predates the general-purpose exception chaining facility. The  {@link #initCause(Throwable)} method is now the preferred meansof recording this information.\n * @param e The possibly null exception that caused the namingoperation to fail. If null, it means this naming exception has no root cause.\n * @see #getRootCause\n * @see #rootException\n * @see #initCause\n */\n","tf":{"freq":{"facil":1,"anyth":1,"except":5,"root":5,"link":1,"possibl":1,"init":2,"predat":1,"general":1,"inform":1,"record":2,"caus":7,"fail":1,"now":1,"chain":1,"name":2,"mean":1,"purpos":1,"method":3,"throwabl":1,"meansof":1,"prefer":1,"namingoper":1},"maxFreq":7,"totalTerms":42},"loc":5}