{"id":11725,"className":"javax.naming.NamingException","methodName":"getRootCause","signature":"\u003cjavax.naming.NamingException: java.lang.Throwable getRootCause()\u003e","javadoc":"/** \n * Retrieves the root cause of this NamingException, if any. The root cause of a naming exception is used when the service provider wants to indicate to the caller a non-naming related exception but at the same time wants to use the NamingException structure to indicate how far the naming operation proceeded. \u003cp\u003e This method predates the general-purpose exception chaining facility. The  {@link #getCause()} method is now the preferred means of obtainingthis information.\n * @return The possibly null exception that caused this namingexception. If null, it means no root cause has been set for this naming exception.\n * @see #setRootCause\n * @see #rootException\n * @see #getCause\n */\n","tf":{"freq":{"caller":1,"obtainingthi":1,"root":6,"structur":1,"link":1,"servic":1,"possibl":1,"use":2,"predat":1,"time":1,"indic":2,"oper":1,"name":6,"relat":1,"proceed":1,"mean":2,"purpos":1,"want":2,"facil":1,"except":8,"far":1,"provid":1,"general":1,"non":1,"inform":1,"caus":8,"now":1,"chain":1,"retriev":1,"method":2,"prefer":1,"namingexcept":1},"maxFreq":8,"totalTerms":61},"loc":3}