{"id":11727,"className":"javax.naming.NamingException","methodName":"getCause","signature":"\u003cjavax.naming.NamingException: java.lang.Throwable getCause()\u003e","javadoc":"/** \n * Returns the cause of this exception.  The cause is the throwable that caused this naming exception to be thrown. Returns \u003ccode\u003enull\u003c/code\u003e if the cause is nonexistent or unknown.\n * @return  the cause of this exception, or \u003ccode\u003enull\u003c/code\u003e if thecause is nonexistent or unknown.\n * @see #initCause(Throwable)\n * @since 1.4\n */\n","tf":{"freq":{"thrown":1,"except":3,"caus":7,"nonexist":2,"name":1,"init":1,"unknown":2,"throwabl":2,"thecaus":1},"maxFreq":7,"totalTerms":20},"loc":3}