{"id":22315,"className":"org.apache.commons.math.MathRuntimeException","methodName":"createIOException","signature":"\u003corg.apache.commons.math.MathRuntimeException: java.io.IOException createIOException(java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new \u003ccode\u003eIOException\u003c/code\u003e with specified nested \u003ccode\u003eThrowable\u003c/code\u003e root cause. \u003cp\u003eThis factory method allows chaining of other exceptions within an \u003ccode\u003eIOException\u003c/code\u003e even for Java 5. The constructor for \u003ccode\u003eIOException\u003c/code\u003e with a cause parameter was introduced only with Java 6.\u003c/p\u003e\n * @param rootCause the exception or error that caused this exceptionto be thrown.\n * @return built exception\n */\n","tf":{"freq":{"exceptionto":1,"thrown":1,"except":7,"error":1,"allow":1,"creat":1,"root":2,"nest":1,"paramet":1,"introduc":1,"specifi":1,"caus":4,"chain":1,"factori":1,"java":2,"even":1,"method":1,"within":1,"construct":1,"throwabl":1,"built":1,"constructor":1},"maxFreq":7,"totalTerms":33},"loc":5}